name: Build and Push Docker Images

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: docker.io
  # DOCKER_USERNAME should contain your Docker Hub username
  # DOCKER_PASSWORD should contain your Docker Hub access token or password
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/pg-backups-to-s3

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres_version: [12, 13, 14, 15, 16, 17]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version without v prefix
        id: version
        run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag,suffix=-pg${{ matrix.postgres_version }}
            type=ref,event=tag,suffix=-pg${{ matrix.postgres_version }}-latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            POSTGRES_VERSION=${{ matrix.postgres_version }}
          tags: |
            ${{ env.IMAGE_NAME }}:pg${{ matrix.postgres_version }}-${{ steps.version.outputs.version }}
            ${{ env.IMAGE_NAME }}:pg${{ matrix.postgres_version }}-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  create-manifest:
    # Creates convenience tags (:latest and :version) that point to PostgreSQL 17 images
    # This allows users to pull the image without specifying a PostgreSQL version
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Extract version without v prefix
        id: version
        run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create and push convenience tags
        run: |
          # Create latest tag (points to pg17-latest)
          docker buildx imagetools create \
            --tag ${{ env.IMAGE_NAME }}:latest \
            ${{ env.IMAGE_NAME }}:pg17-latest
          
          # Create version tag (points to pg17-version)
          docker buildx imagetools create \
            --tag ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }} \
            ${{ env.IMAGE_NAME }}:pg17-${{ steps.version.outputs.version }} 